8 as a new user i can create a local account
AY2324S1-CS2103T-T13-3/tp pull request #124
Opened 2023-10-17 14:19 UTC by jianyangg

Close #8; adds the `register` command.

2023-10-18 04:55 UTC, B-enguin reviewed
Some general feedback

2023-10-18 04:55 UTC, B-enguin commented on src/main/java/seedu/address/logic/commands/user/UserRegisterCommand.java
Should this file have unit test done

2023-10-18 04:55 UTC, B-enguin commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +            return new UserRegisterCommandParser().parse(arguments);
Perhaps add testing to the AdressBookParserTest for this new command word

2023-10-18 04:55 UTC, B-enguin commented on src/main/java/seedu/address/model/ModelManager.java
> +        return userPrefs.userMatches(user);
Add testing to `ModelManagerTest`

2023-10-18 04:55 UTC, B-enguin commented on src/main/java/seedu/address/model/UserPrefs.java
Add testing for this file

2023-10-18 04:55 UTC, B-enguin commented on src/main/java/seedu/address/model/user/Password.java
Add testing

2023-10-18 04:55 UTC, B-enguin commented on src/main/java/seedu/address/model/user/User.java
Add testing

2023-10-19 00:09 UTC, juliusgambe requested changes, later dismissed
I think we moved instance creation to the command itself cc: @B-enguin

2023-10-19 00:14 UTC, juliusgambe reviewed
General feedback

2023-10-19 00:14 UTC, juliusgambe commented on src/main/java/seedu/address/logic/parser/user/UserLoginCommandParser.java
> +        User user = new User(username, password, true);
I think instance creation has been relegated to execute method.

2023-10-19 00:14 UTC, juliusgambe commented on src/main/java/seedu/address/model/UserPrefs.java
> +    public User getStoredUser() {
We may need to migrate this JSON Serializable

2023-10-19 02:55 UTC, merged